// 检索地市信息
var jobMessage = [
  {
    'regid': '2',
    'parid': '1',
    'regname': '技术/设计',
    'regtype': '1',
    'ageid': '0'
  }, {
    'regid': '3',
    'parid': '1',
    'regname': '高中家教',
    'regtype': '1',
    'ageid': '0'
  }, {
    'regid': '4',
    'parid': '1',
    'regname': '初中家教',
    'regtype': '1',
    'ageid': '0'
  }, {
    'regid': '5',
    'parid': '1',
    'regname': '小学家教',
    'regtype': '1',
    'ageid': '0'
  }, {
    'regid': '6',
    'parid': '1',
    'regname': '音乐老师',
    'regtype': '1',
    'ageid': '0'
  }, {
    'regid': '7',
    'parid': '1',
    'regname': '其他',
    'regtype': '1',
    'ageid': '0'
  }, {
    'regid': '1',
    'parid': '2',
    'regname': 'Java产品设计',
    'regtype': '2',
    'ageid': '0'
  }, {
    'regid': '2',
    'parid': '2',
    'regname': 'Web前端',
    'regtype': '2',
    'ageid': '0'
  }, {
    'regid': '3',
    'parid': '2',
    'regname': '算法工程师',
    'regtype': '2',
    'ageid': '0'
  }, {
    'regid': '4',
    'parid': '2',
    'regname': 'UI设计',
    'regtype': '2',
    'ageid': '0'
  }, {
    'regid': '5',
    'parid': '2',
    'regname': '平面设计',
    'regtype': '2',
    'ageid': '0'
  }, {
    'regid': '6',
    'parid': '2',
    'regname': '交互设计',
    'regtype': '2',
    'ageid': '0'
  }, {
    'regid': '1',
    'parid': '3',
    'regname': '语文辅导',
    'regtype': '2',
    'ageid': '0'
  }, {
    'regid': '2',
    'parid': '3',
    'regname': '数学辅导',
    'regtype': '2',
    'ageid': '0'
  }, {
    'regid': '3',
    'parid': '3',
    'regname': '英语辅导',
    'regtype': '2',
    'ageid': '0'
  }, {
    'regid': '4',
    'parid': '3',
    'regname': '化学辅导',
    'regtype': '2',
    'ageid': '0'
  }, {
    'regid': '5',
    'parid': '3',
    'regname': '物理辅导',
    'regtype': '2',
    'ageid': '0'
  }, {
    'regid': '6',
    'parid': '3',
    'regname': '生物辅导',
    'regtype': '2',
    'ageid': '0'
  }, {
    'regid': '1',
    'parid': '4',
    'regname': '语文辅导',
    'regtype': '2',
    'ageid': '0'
  }, {
    'regid': '2',
    'parid': '4',
    'regname': '数学辅导',
    'regtype': '2',
    'ageid': '0'
  }, {
    'regid': '3',
    'parid': '4',
    'regname': '英语辅导',
    'regtype': '2',
    'ageid': '0'
  }, {
    'regid': '4',
    'parid': '4',
    'regname': '化学辅导',
    'regtype': '2',
    'ageid': '0'
  }, {
    'regid': '5',
    'parid': '4',
    'regname': '物理辅导',
    'regtype': '2',
    'ageid': '0'
  }, {
    'regid': '6',
    'parid': '4',
    'regname': '生物辅导',
    'regtype': '2',
    'ageid': '0'
  }, {
    'regid': '1',
    'parid': '5',
    'regname': '语文辅导',
    'regtype': '2',
    'ageid': '0'
  }, {
    'regid': '2',
    'parid': '5',
    'regname': '数学辅导',
    'regtype': '2',
    'ageid': '0'
  }, {
    'regid': '3',
    'parid': '5',
    'regname': '外语辅导',
    'regtype': '2',
    'ageid': '0'
  }, {
    'regid': '1',
    'parid': '6',
    'regname': '钢琴老师',
    'regtype': '2',
    'ageid': '0'
  }, {
    'regid': '2',
    'parid': '6',
    'regname': '吉他老师',
    'regtype': '2',
    'ageid': '0'
  }, {
    'regid': '3',
    'parid': '6',
    'regname': '口琴老师',
    'regtype': '2',
    'ageid': '0'
  }, {
    'regid': '4',
    'parid': '6',
    'regname': '小提琴老师',
    'regtype': '2',
    'ageid': '0'
  }, {
    'regid': '5',
    'parid': '6',
    'regname': '古筝老师',
    'regtype': '2',
    'ageid': '0'
  }, {
    'regid': '6',
    'parid': '6',
    'regname': '声乐老师',
    'regtype': '2',
    'ageid': '0'
  }, {
    'regid': '1',
    'parid': '7',
    'regname': '销售',
    'regtype': '2',
    'ageid': '0'
  }, {
    'regid': '2',
    'parid': '7',
    'regname': '运营',
    'regtype': '2',
    'ageid': '0'
  }, {
    'regid': '3',
    'parid': '7',
    'regname': '策划',
    'regtype': '2',
    'ageid': '0'
  }, {
    'regid': '4',
    'parid': '7',
    'regname': '推广',
    'regtype': '2',
    'ageid': '0'
  }]
export { jobMessage }
